name: surfemb
dependencies:
  - python=3.8
  - pip
  - pytorch::pytorch
  - pytorch::torchvision
  - pyg::pytorch-scatter
  - conda-forge::imgaug
  - conda-forge::albumentations
  - numpy
  - matplotlib
  - scipy
  - pip:
      - tqdm
      - moderngl
      - pytorch_lightning==1.5.0
      - wandb
      - trimesh
      - rtree
      - pymeshlab